name: HugFirst
favicon: null
layout_spectrum: 0.2525870322715491
typography_spectrum: 0.6120433460455388
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.695146644487977
  lightness: 0.5488997511565685
  saturation: 0.045455219224095345
  rhythmicContrast: 0.49049350689165294
purpose: []
